//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class CEST
    {
        public int Id { get; set; }
        public string Item { get; set; }
        public string NumeroCest { get; set; }
        public string Ncm { get; set; }
        public string IdDoSegmento { get; set; }
        public string SegmentoMercadorias { get; set; }
        public string DescricaoCest { get; set; }
        public string Utrib { get; set; }
        public string UtribDescricao { get; set; }
    }
}
