//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class IPI
    {
        public int IdIpi { get; set; }
        public Nullable<int> CST { get; set; }
        public Nullable<decimal> vBC { get; set; }
        public Nullable<decimal> pIPI { get; set; }
        public Nullable<decimal> vIPI { get; set; }
        public Nullable<int> IdProduto { get; set; }
    
        public virtual Produto Produto { get; set; }
    }
}
