//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using DAL.Database;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ProdutosAuditadosEntities : DbContext
    {
        public ProdutosAuditadosEntities()
            : base("name=ProdutosAuditadosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Empresa> Empresa { get; set; }
        public virtual DbSet<Produto> Produto { get; set; }
        public virtual DbSet<COFINS> COFINS { get; set; }
        public virtual DbSet<ICMS_00> ICMS_00 { get; set; }
        public virtual DbSet<ICMS_10> ICMS_10 { get; set; }
        public virtual DbSet<ICMS_20> ICMS_20 { get; set; }
        public virtual DbSet<ICMS_30> ICMS_30 { get; set; }
        public virtual DbSet<ICMS_40> ICMS_40 { get; set; }
        public virtual DbSet<ICMS_41> ICMS_41 { get; set; }
        public virtual DbSet<ICMS_50> ICMS_50 { get; set; }
        public virtual DbSet<ICMS_51> ICMS_51 { get; set; }
        public virtual DbSet<ICMS_60> ICMS_60 { get; set; }
        public virtual DbSet<ICMS_70> ICMS_70 { get; set; }
        public virtual DbSet<ICMS_90> ICMS_90 { get; set; }
        public virtual DbSet<IPI> IPI { get; set; }
        public virtual DbSet<PIS> PIS { get; set; }
    }
}
