//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.COFINS = new HashSet<COFINS>();
            this.ICMS_00 = new HashSet<ICMS_00>();
            this.ICMS_10 = new HashSet<ICMS_10>();
            this.ICMS_20 = new HashSet<ICMS_20>();
            this.ICMS_30 = new HashSet<ICMS_30>();
            this.ICMS_40 = new HashSet<ICMS_40>();
            this.ICMS_41 = new HashSet<ICMS_41>();
            this.ICMS_50 = new HashSet<ICMS_50>();
            this.ICMS_51 = new HashSet<ICMS_51>();
            this.ICMS_60 = new HashSet<ICMS_60>();
            this.ICMS_70 = new HashSet<ICMS_70>();
            this.ICMS_90 = new HashSet<ICMS_90>();
            this.IPI = new HashSet<IPI>();
            this.PIS = new HashSet<PIS>();
        }
    
        public int IdProduto { get; set; }
        public string CodigoProduto { get; set; }
        public string Descricao { get; set; }
        public string Ean { get; set; }
        public string Ncm { get; set; }
        public string Cfop { get; set; }
        public string Cest { get; set; }
        public string DescricaodeNcmTipi { get; set; }
        public string DescricaoCest { get; set; }
        public string PaisDeRegistro { get; set; }
        public string Fabricante { get; set; }
        public string Distribuidores { get; set; }
        public string Marca { get; set; }
        public string SegmentoMercadorias { get; set; }
        public string Imagem { get; set; }
        public string Status { get; set; }
        public string Observacoes { get; set; }
        public int IdEmpresa { get; set; }
        public string UnidadeComercial { get; set; }
    
    //    public virtual Empresa Empresa { get; set; }
   //     [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<COFINS> COFINS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMS_00> ICMS_00 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMS_10> ICMS_10 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMS_20> ICMS_20 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMS_30> ICMS_30 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMS_40> ICMS_40 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMS_41> ICMS_41 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMS_50> ICMS_50 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMS_51> ICMS_51 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMS_60> ICMS_60 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMS_70> ICMS_70 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ICMS_90> ICMS_90 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IPI> IPI { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PIS> PIS { get; set; }
    }
}
