//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRODUTOS
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public string UNID { get; set; }
        public string EAN { get; set; }
        public string NCM { get; set; }
        public string FATOR { get; set; }
        public string DESCRICAO { get; set; }
        public string ID_TIPOPROD { get; set; }
        public string ID_CLASSIFICACAO { get; set; }
        public string IMAGEM_URL { get; set; }
    }
}
