//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RegistrosEANEntities : DbContext
    {
        public RegistrosEANEntities()
            : base("name=RegistrosEANEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CEST> CEST { get; set; }
        public virtual DbSet<IBPT> IBPT { get; set; }
        public virtual DbSet<PRODUTOS> PRODUTOS { get; set; }
        public virtual DbSet<ProdutosDrogaria> ProdutosDrogaria { get; set; }
        public virtual DbSet<TIPI> TIPI { get; set; }
        public virtual DbSet<Classificacao> Classificacao { get; set; }
    }
}
