//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPI
    {
        public int Id { get; set; }
        public string Ncm { get; set; }
        public string Descricao { get; set; }
        public string Aliquota { get; set; }
        public string Ex1 { get; set; }
        public string Ex2 { get; set; }
        public string Ex3 { get; set; }
        public string Ex4 { get; set; }
        public string Ex5 { get; set; }
        public string Ex6 { get; set; }
        public string Ex7 { get; set; }
        public string Ex8 { get; set; }
        public string Ex9 { get; set; }
        public string Ex10 { get; set; }
        public string Ex11 { get; set; }
        public string Ex12 { get; set; }
    }
}
